# Generated by Django 4.2.19 on 2025-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_video', models.FileField(upload_to='videos/original/')),
                ('compressed_video', models.FileField(blank=True, null=True, upload_to='videos/compressed/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('expired', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Video',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
